# Generated by Django 4.2.3 on 2023-07-15 18:09

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='media/<function get_file_path at 0x0000022DEE80B060>', variations={}, verbose_name='Imagem'),
        ),
    ]
